name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
       docker login --username Mufeth7 --password ${{ secrets.PASS }}
       docker build . --tag ghcr.io/mufeth7/huelogs-ghcr:latest
       docekr push ghcr.io/mufeth7/huelogs-ghcr:latest