name: Create GitHub Release on Push

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
          node-version: ${{ steps.node-version.outputs.node_version }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Get version from release
      id: get_version
      run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV


  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN}}
          
      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/mufeth7/huelogs:${{ env.VERSION }} 

      - name: Push Docker image
        run: |
          docker push ghcr.io/mufeth7/huelogs:${{ env.VERSION }} 
        env:  
          REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}